"""Builds the dataset report (rows before/after cleaning, columns, missing values, data dictionary) + charts."""
import os
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from .config import CHART_DIR, ROUTES
TEAL, AMBER, INK, RED = "#127c82", "#e8a317", "#1d2733", "#c0392b"
DICT = {"trip_id": ("Identifier", "Unique trip code"), "date": ("Date", "Date of the trip (2025)"), "route_id": ("Category", "One of 12 routes"),
        "transport_mode": ("Category", "Bus, Tram, Metro or Train"), "distance_km": ("Number", "Route length (km)"), "num_stops": ("Number", "Stops on the route"),
        "scheduled_headway_min": ("Number", "Planned gap between vehicles (min)"), "day_of_week": ("Category", "Monday to Sunday"), "month": ("Number", "1-12"),
        "hour": ("Number", "Hour the trip started (0-23)"), "is_holiday": ("Flag 0/1", "Public holiday"), "temperature": ("Number", "Temperature (°C)"),
        "weather": ("Category", "Clear, Rain, Fog, Snow, Storm"), "traffic_index": ("Number", "Congestion 0-100"), "passenger_load": ("Number", "Occupancy %"),
        "incident": ("Flag 0/1", "Accident / breakdown reported"), "delay_minutes": ("Number (TARGET)", "Minutes behind schedule"),
        "is_peak": ("Flag 0/1 (new)", "Rush-hour trip - engineered"), "is_weekend": ("Flag 0/1 (new)", "Saturday/Sunday - engineered"),
        "is_delayed": ("Flag 0/1 (new, TARGET)", "Delay above 5 min - engineered")}

def build(raw, df, rep):
    c = rep["counts"]; imp = c["imputed"]; tot_imp = sum(imp.values())
    r = {"source": "Simulated dataset generated by generate_dataset.py (random seed 42) using realistic rules; replaceable by a real CSV with the same columns",
         "rows_raw": len(raw), "rows_clean": len(df), "rows_removed": len(raw) - len(df), "cols_raw": raw.shape[1], "cols_clean": df.shape[1],
         "date_min": str(df.date.min())[:10], "date_max": str(df.date.max())[:10], "routes": int(df.route_id.nunique()), "modes": int(df.transport_mode.nunique()),
         "missing_cells_before": int(raw.isna().sum().sum()), "missing_cells_after": rep["missing_after"], "imputed_total": tot_imp,
         "duplicates": c["duplicates"], "label_fixes": c["label_fixes"], "outliers": c["outliers_capped"], "cap_value": c["cap_value"],
         "pct_delayed": round(float(df.is_delayed.mean() * 100), 1)}
    r["missing_table"] = [{"column": k, "before": int(raw[k].isna().sum()), "pct": round(float(raw[k].isna().mean() * 100), 1), "after": int(df[k].isna().sum())}
                          for k in raw.columns if raw[k].isna().sum() > 0]
    r["dictionary"] = [{"column": k, "type": DICT.get(k, ("", ""))[0], "meaning": DICT.get(k, ("", ""))[1],
                        "example": str(df[k].iloc[0])} for k in df.columns]
    r["by_mode"] = [{"mode": m, "rows": int(n), "avg_delay": round(float(df[df.transport_mode == m].delay_minutes.mean()), 2)} for m, n in df.transport_mode.value_counts().items()]
    r["funnel"] = [{"step": "Raw file", "rows": len(raw)}, {"step": f"− {c['duplicates']} duplicates", "rows": len(raw) - c["duplicates"]},
                   {"step": "Imputation / outlier capping (rows kept)", "rows": len(df)}, {"step": "Clean dataset", "rows": len(df)}]
    # ---- charts ----
    fig, ax = plt.subplots(1, 2, figsize=(10, 3.8))
    labels = ["Raw file", "Duplicates\nremoved", "Clean data"]; vals = [len(raw), c["duplicates"], len(df)]
    ax[0].bar(labels, vals, color=[INK, RED, TEAL])
    for i, v in enumerate(vals): ax[0].text(i, v, f"{v:,}", ha="center", va="bottom", fontweight="bold")
    ax[0].set_title("Rows before and after cleaning"); ax[0].set_ylim(0, len(raw) * 1.12)
    mt = pd.DataFrame(r["missing_table"]).set_index("column"); x = np.arange(len(mt)); w = .38
    ax[1].bar(x - w/2, mt.before, w, color=AMBER, label="before"); ax[1].bar(x + w/2, mt.after, w, color=TEAL, label="after")
    ax[1].set_xticks(x); ax[1].set_xticklabels(mt.index, rotation=15); ax[1].set_title("Missing values before vs after cleaning"); ax[1].legend()
    plt.tight_layout(); plt.savefig(os.path.join(CHART_DIR, "data_funnel.png"), dpi=110); plt.close()
    fig, ax = plt.subplots(1, 3, figsize=(10, 3.4))
    for a, (col, ttl) in zip(ax, [("transport_mode", "Trips per mode"), ("weather", "Trips per weather"), ("day_of_week", "Trips per weekday")]):
        v = df[col].value_counts(); 
        if col == "day_of_week": v = v.reindex(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])
        a.bar(v.index, v.values, color=TEAL); a.set_title(ttl); a.tick_params(axis="x", rotation=35)
    plt.tight_layout(); plt.savefig(os.path.join(CHART_DIR, "composition.png"), dpi=110); plt.close()
    return r
